[package]
name = "massa-client"
version = "0.1.0"
edition = "2021"
build = "../build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
atty = "0.2"
config = "0.11"
console = "0.15"
dialoguer = { version = "0.9", git = "https://github.com/yvan-sraka/dialoguer.git", branch = "completion-feature", features = ["history", "completion"] }
directories = "4.0"
erased-serde = "0.3"
futures = "0.3"
glob = "0.3.0"
jsonrpc-core-client = { version = "18.0", features = ["http", "tls"] }
lazy_static = "1.4"
paw = "1.0"
rev_lines = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = { version = "0.3", features = ["paw"] }
strum = "0.22"
strum_macros = "0.22"
tokio = { version = "1.15", features = ["full"] }
# custom modules
massa_models = { path = "../massa-models" }
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }
massa_wallet = { path = "../massa-wallet" }

[target.'cfg(not(windows))'.dependencies]
tilde-expand = "0.1.1"

[dev-dependencies]
assert_cmd = "2.0"
serial_test = "0.5"
toml_edit = "0.8"

[features]
hash-prefix = ["massa_models/hash-prefix", "massa_signature/hash-prefix"]
instrument = ["tokio/tracing", "massa_models/instrument", "massa_time/instrument"]
