[package]
name = "massa_consensus_exports"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
displaydoc = "0.2"
num = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.19", features = ["full"] }
tracing = "0.1"
tempfile = { version = "3.3", optional = true }    # use with testing feature
# custom modules
massa_cipher = { path = "../massa-cipher" }
massa_execution_exports = { path = "../massa-execution-exports" }
massa_graph = { path = "../massa-graph" }
massa_logging = { path = "../massa-logging" }
massa_models = { path = "../massa-models" }
massa_pool = { path = "../massa-pool" }
massa_proof_of_stake_exports = { path = "../massa-proof-of-stake-exports" }
massa_protocol_exports = { path = "../massa-protocol-exports" }
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }

[dev-dependencies]
massa_models = { path = "../massa-models", features = ["testing"] }

# for more information on what are the following features used for, see the cargo.toml at workspace level
[features]
instrument = [
    "tokio/tracing",
    "massa_graph/instrument",
    "massa_models/instrument",
    "massa_pool/instrument",
    "massa_proof_of_stake_exports/instrument",
    "massa_protocol_exports/instrument",
    "massa_time/instrument",
]
sandbox = ["massa_proof_of_stake_exports/sandbox"]
testing = [
    "massa_models/testing",
    "massa_execution_exports/testing",
    "tempfile",
]
