[package]
name = "massa_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonrpc-core-client = { git = "https://github.com/massalabs/jsonrpc", features = ["http", "tls"] }
tokio = { version = "1.21", features = ["full"] }
massa_models = { path = "../massa-models" }
serde = { version = "1.0", features = ["derive"] }
