[package]
name = "massa_sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
jsonrpc-core-client = { version = "18.0", features = ["http", "tls"] }
tokio = { version = "1.19", features = ["full"] }
massa_models = { path = "../massa-models" }
massa_signature = { path = "../massa-signature" }
serde = { version = "1.0", features = ["derive"] }
