[package]
name = "massa_execution_worker"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
rand = "0.8"
rand_xoshiro = "0.6"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
tracing = "0.1"
serde_json = "1.0"
num = { version = "0.4", features = ["serde"] }
# custom modules
massa_async_pool = { path = "../massa-async-pool" }
massa_executed_ops = { path = "../massa-executed-ops" }
massa_execution_exports = { path = "../massa-execution-exports" }
massa_models = { path = "../massa-models" }
massa_storage = { path = "../massa-storage" }
massa_hash = { path = "../massa-hash" }
massa-sc-runtime = { git = "https://github.com/massalabs/massa-sc-runtime", tag = "v0.8.2" }
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }
massa_ledger_exports = { path = "../massa-ledger-exports" }
massa_pos_exports = { path = "../massa-pos-exports" }
massa_final_state = { path = "../massa-final-state" }

[dev-dependencies]
serial_test = "0.9"
tempfile = "3.2"
# custom modules with testing enabled
massa_pos_worker = { path = "../massa-pos-worker" }
massa_ledger_worker = { path = "../massa-ledger-worker" }

[features]
sandbox = ["massa_async_pool/sandbox"]
testing = ["massa_execution_exports/testing", "massa_ledger_exports/testing", "massa_pos_exports/testing", "massa_pos_worker/testing", "massa_ledger_worker/testing", "massa_final_state/testing"]