[package]
name = "massa_protocol_worker"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.10"
serde_json = "1.0"
tokio = { version = "1.19", features = ["full"] }
tracing = "0.1"
# custom modules
massa_hash = { path = "../massa-hash" }
massa_logging = { path = "../massa-logging" }
massa_models = { path = "../massa-models" }
massa_network_exports = { path = "../massa-network-exports" }
massa_protocol_exports = { path = "../massa-protocol-exports" }
massa_storage = { path = "../massa-storage" }
massa_time = { path = "../massa-time" }

[dev-dependencies]
lazy_static = "1.4"
futures = "0.3"
massa_signature = { path = "../massa-signature" }
serial_test = "0.8"


# for more information on what are the following features used for, see the cargo.toml at workspace level
[features]
instrument = [
    "tokio/tracing",
    "massa_models/instrument",
    "massa_network_exports/instrument",
    "massa_protocol_exports/instrument",
    "massa_time/instrument",
]
