[package]
name = "massa_api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
displaydoc = "0.2"
futures = "0.3"
jsonrpc-core = "18.0"
jsonrpc-derive = "18.0"
jsonrpc-http-server = "18.0"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
tokio = { version = "1.19", features = ["full"] }
tracing = "0.1"
# custom modules
massa_consensus_exports = { path = "../massa-consensus-exports" }
massa_execution_exports = { path = "../massa-execution-exports" }
massa_graph = { path = "../massa-graph" }
massa_hash = { path = "../massa-hash" }
massa_models = { path = "../massa-models" }
massa_network_exports = { path = "../massa-network-exports" }
massa_pool = { path = "../massa-pool" }
massa_serialization = { path = "../massa-serialization"}
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }

# for more information on what are the following features used for, see the cargo.toml at workspace level
[features]
instrument = [
    "tokio/tracing",
    "massa_consensus_exports/instrument",
    "massa_graph/instrument",
    "massa_models/instrument",
    "massa_network_exports/instrument",
    "massa_pool/instrument",
    "massa_time/instrument",
]
