[package]
name = "massa_logging"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
tracing = "0.1"

[dev-dependencies]
pretty_assertions = "1.2"
serial_test = "0.9"
