[package]
name = "massa_models"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

[dependencies]
displaydoc = "0.2"
integer-encoding = "3.0"
lazy_static = "1.4"
num_enum = "0.5"
rust_decimal = "1.25"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1.0"
num = { version = "0.4", features = ["serde"] }
directories = "4.0"
config = "0.11"
bs58 = { version = "0.4", features = ["check"] }
nom = "7.1"

# custom modules
massa_hash = { path = "../massa-hash" }
massa_serialization = { path = "../massa-serialization" }
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }

[dev-dependencies]
serial_test = "0.8"

# for more information on what are the following features used for, see the cargo.toml at workspace level
[features]
hash-prefix = ["massa_signature/hash-prefix"]
instrument = ["massa_time/instrument"]
sandbox = []
testing = []
