name: CD

on:
  push:
    tags:
      - TEST.*

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  release:
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest, windows-latest]
        include:
          - os: ubuntu-18.04
            target: x86_64-unknown-linux-musl
            name: release_linux.tar.gz
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            name: release_windows.zip
          - os: macOS-latest
            target: x86_64-apple-darwin
            name: release_macos.tar.gz
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          target: ${{ matrix.target }}
          override: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Package
        shell: bash
        run: |
          mkdir massa && cd massa && mkdir massa-node && mkdir massa-client
          cp -v ../target/release/massa-node massa-node/massa-node
          cp -v ../target/release/massa-client massa-client/massa-client
          cp -rv ../massa-node/config massa-node/config
          cp -rv ../massa-node/base_config massa-node/base_config
          cp -rv ../massa-node/storage massa-node/storage
          cp -rv ../massa-client/config massa-client/config
          cp -rv ../massa-client/base_config massa-client/base_config
          cd ..
          if [[ "${{ matrix.os }}" == "windows-latest" ]]
          then
            7z a massa_${GITHUB_REF/refs\/tags\//}_${{ matrix.name }} massa
          else
            tar czvf massa_${GITHUB_REF/refs\/tags\//}_${{ matrix.name }} massa
          fi
          cd -
      - name: Publish
        uses: softprops/action-gh-release@v1
        with:
          files: 'massa_*'
