[package]
name = "massa_consensus_worker"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
tokio = { version = "1.19", features = ["full"] }
tracing = "0.1"
# custom modules
massa_consensus_exports = { path = "../massa-consensus-exports" }
massa_cipher = { path = "../massa-cipher" }
massa_graph = { path = "../massa-graph" }
massa_hash = { path = "../massa-hash" }
massa_logging = { path = "../massa-logging" }
massa_models = { path = "../massa-models" }
massa_storage = { path = "../massa-storage" }
massa_proof_of_stake_exports = { path = "../massa-proof-of-stake-exports" }
massa_protocol_exports = { path = "../massa-protocol-exports" }
massa_signature = { path = "../massa-signature" }
massa_time = { path = "../massa-time" }

[dev-dependencies]
serial_test = "0.8"
tempfile = "3.3"
massa_models = { path = "../massa-models", features = ["testing"] }
massa_execution_exports = { path = "../massa-execution-exports", features = [
    "testing",
] }
massa_consensus_exports = { path = "../massa-consensus-exports", features = [
    "testing",
] }
massa_pool = { path = "../massa-pool" }
num = { version = "0.4", features = ["serde"] }
rand = "0.8"
futures = "0.3"


# for more information on what are the following features used for, see the cargo.toml at workspace level
[features]
instrument = [
    "tokio/tracing",
    "massa_consensus_exports/instrument",
    "massa_graph/instrument",
    "massa_models/instrument",
    "massa_proof_of_stake_exports/instrument",
    "massa_protocol_exports/instrument",
    "massa_time/instrument",
]
sandbox = ["massa_consensus_exports/sandbox"]
