[package]
name = "massa_consensus_worker"
version = "0.1.0"
authors = ["Massa Labs <info@massa.net>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0"
tokio = { version = "1.21", features = ["full"] }
tracing = "0.1"
# custom modules
massa_consensus_exports = { path = "../massa-consensus-exports" }
massa_graph = { path = "../massa-graph" }
massa_logging = { path = "../massa-logging" }
massa_models = { path = "../massa-models" }
massa_storage = { path = "../massa-storage" }
massa_protocol_exports = { path = "../massa-protocol-exports" }
massa_time = { path = "../massa-time" }

[dev-dependencies]
serial_test = "0.9"
#tempfile = "3.3"
parking_lot = { version = "0.12", features = ["deadlock_detection"] }
massa_models = { path = "../massa-models", features = ["testing"] }
massa_execution_exports = { path = "../massa-execution-exports", features = [
    "testing",
] }
massa_consensus_exports = { path = "../massa-consensus-exports", features = [
    "testing",
] }
massa_pos_exports = { path = "../massa-pos-exports", features = ["testing"]}
massa_pos_worker = { path = "../massa-pos-worker" }
massa_pool_exports = { path = "../massa-pool-exports" }
massa_serialization = { path = "../massa-serialization"}
massa_hash = { path = "../massa-hash" }
massa_signature = { path = "../massa-signature" }
massa_cipher = { path = "../massa-cipher" }
massa_storage = { path = "../massa-storage" }
#num = { version = "0.4", features = ["serde"] }
#rand = "0.8"
#futures = "0.3"


# for more information on what are the following features used for, see the cargo.toml at workspace level
[features]
sandbox = ["massa_consensus_exports/sandbox", "massa_protocol_exports/sandbox" ]
testing = [
    "massa_consensus_exports/testing",
    "massa_execution_exports/testing",
    "massa_models/testing",
    "massa_pool_exports/testing",
    "massa_protocol_exports/testing"
]